language: objective-c
osx_image: xcode11.2

before_install:
  - brew outdated python || brew upgrade python
  - pip2 install pyflakes
  - pip3 install pyflakes
  - gem install rubocop
  - brew install shellcheck
  - brew install luarocks
  - luarocks install luacheck
  - brew outdated node || brew upgrade node
  - npm install -g jshint
  - brew install cpanminus && sudo cpanm Mozilla::CA
  - brew install clisp
  - brew outdated golang || brew upgrade golang
  - go get -u golang.org/x/lint/golint
  - brew cask install racket
  - raco pkg install --deps search-auto rackjure
install:
  - export PATH="$PATH:${GOROOT:-$HOME/go}/bin"

script: ./.test.py
